//! Integration tests exercising real FFmpeg through the safe wrapper.
//!
//! The fixture (`tests/fixtures/sample.mkv`) is a deterministic 2-second,
//! 160x120, 10 fps MPEG-4/Matroska file generated by
//! `scripts/generate-fixture.sh` (LGPL-native encoder, synthetic source).
//! No real camera and no GPL component is involved.

// Tests assert with panicking macros by design.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::PathBuf;
use std::time::Duration;

use nian_domain::MediaType;
use nian_media::{MediaError, MediaSource, Probe};
use nian_media_ffmpeg::{FfmpegBackend, InterruptHandle, MatroskaMuxer, MediaInput};

fn fixture_path() -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.extend(["tests", "fixtures", "sample.mkv"]);
    assert!(
        path.is_file(),
        "fixture missing at {}; run scripts/generate-fixture.sh",
        path.display()
    );
    path
}

fn fixture_source() -> MediaSource {
    MediaSource::File(fixture_path())
}

#[test]
fn runtime_abi_matches_compiled_bindings() {
    let versions = nian_media_ffmpeg::runtime_versions().expect("abi check");
    assert_eq!(
        versions.avformat,
        nian_ffmpeg_sys::LIBAVFORMAT_VERSION_MAJOR
    );
    assert_eq!(versions.avcodec, nian_ffmpeg_sys::LIBAVCODEC_VERSION_MAJOR);
    assert_eq!(versions.avutil, nian_ffmpeg_sys::LIBAVUTIL_VERSION_MAJOR);
}

#[test]
fn probe_reports_fixture_streams() {
    let backend = FfmpegBackend::new().unwrap();
    let report = backend.probe(&fixture_source()).unwrap();

    assert_eq!(report.format_name, "matroska,webm");

    let video = report.video_stream().expect("fixture has a video stream");
    assert_eq!(video.media_type, MediaType::Video);
    assert_eq!(video.codec_name, "mpeg4");
    assert_eq!(video.width, Some(160));
    assert_eq!(video.height, Some(120));
    assert!(video.time_base.is_some());

    let duration = report.duration.expect("fixture duration is known");
    assert!(
        Duration::from_millis(1500) <= duration && duration <= Duration::from_millis(2500),
        "unexpected duration {duration:?}"
    );
}

#[test]
fn reading_packets_yields_keyframed_monotonic_video() {
    let interrupt = InterruptHandle::new();
    let mut input = MediaInput::open(&fixture_source(), &interrupt).unwrap();

    let mut video_packets = 0usize;
    let mut last_dts: Option<i64> = None;
    let mut first_is_keyframe = None;

    while let Some(packet) = input.next_packet().unwrap() {
        assert!(!packet.data.is_empty(), "packet payload must not be empty");
        if packet.metadata.stream_index == 0 {
            video_packets += 1;
            if first_is_keyframe.is_none() {
                first_is_keyframe = Some(packet.metadata.keyframe);
            }
            let dts = packet.metadata.dts.expect("mpeg4 dts present");
            if let Some(previous) = last_dts {
                assert!(
                    dts > previous,
                    "dts must strictly increase, {previous} -> {dts}"
                );
            }
            last_dts = Some(dts);
        }
    }

    assert!(
        first_is_keyframe.unwrap_or(false),
        "first video packet must be a keyframe"
    );
    // 2 seconds at 10 fps.
    assert!(
        video_packets >= 20,
        "expected ~20 video packets, got {video_packets}"
    );
}

#[test]
fn remux_to_matroska_produces_valid_output() {
    let interrupt = InterruptHandle::new();
    let mut input = MediaInput::open(&fixture_source(), &interrupt).unwrap();

    let output_dir = tempfile::tempdir().unwrap();
    let output_path = output_dir.path().join("remuxed.mkv");

    let mut muxer = MatroskaMuxer::create(&mut input, &output_path, &interrupt).unwrap();
    let mut written = 0usize;
    while let Some(packet) = input.next_packet().unwrap() {
        muxer.write_packet(&packet).unwrap();
        written += 1;
    }
    let finalized = muxer.finalize().unwrap();
    assert_eq!(finalized, output_path);
    assert!(written >= 20);

    let backend = FfmpegBackend::new().unwrap();
    let report = backend.probe(&MediaSource::file(&output_path)).unwrap();
    assert_eq!(report.format_name, "matroska,webm");
    let video = report.video_stream().unwrap();
    assert_eq!(video.codec_name, "mpeg4");
    assert_eq!(video.width, Some(160));

    // The output file must be independently playable/probeable with sane
    // duration (master spec M2 acceptance, exercised early here).
    let duration = report.duration.unwrap();
    assert!(
        Duration::from_millis(1500) <= duration && duration <= Duration::from_millis(2500),
        "remuxed duration {duration:?}"
    );
}

#[test]
fn cancelled_interrupt_aborts_open() {
    let interrupt = InterruptHandle::new();
    interrupt.cancel();

    let result = MediaInput::open(&fixture_source(), &interrupt);
    match result {
        Err(MediaError::Interrupted { .. }) => {}
        Err(other) => panic!("expected Interrupted, got {other:?}"),
        Ok(_) => panic!("open must fail when the interrupt is pre-cancelled"),
    }
}

#[test]
fn deadline_aborts_open() {
    let interrupt = InterruptHandle::new();
    interrupt.set_deadline_from_now(Duration::from_millis(0));

    let result = MediaInput::open(&fixture_source(), &interrupt);
    match result {
        // The abort surfaces either as Interrupted or as a plain open error
        // carrying the interrupt flag, depending on where FFmpeg checks the
        // callback first; both are acceptable, a hang is not.
        Err(MediaError::Interrupted { .. }) => {}
        Err(MediaError::OpenFailed { .. }) => {}
        Err(other) => panic!("unexpected error {other:?}"),
        Ok(_) => panic!("open must fail with an expired deadline"),
    }
}
