//! Integration tests exercising real FFmpeg through the safe wrapper.
//!
//! Fixtures live in `tests/fixtures/` and are generated by
//! `scripts/generate-fixture.sh` (LGPL-native encoders, synthetic sources):
//!
//! * `sample.mkv` — 2 s, 160x120, 10 fps MPEG-4 video only;
//! * `sample_av.mkv` — same video plus a native-AAC audio track, to prove
//!   stream selection/mapping when not every input stream is recorded.
//!
//! No real camera and no GPL component is involved.

// Tests assert with panicking macros by design.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};
use std::time::Duration;

use nian_domain::{MediaStreamInfo, MediaType};
use nian_media::{MediaError, MediaSource, Probe};
use nian_media_ffmpeg::{FfmpegBackend, InterruptHandle, MatroskaMuxer, MediaInput};

fn fixture_path(name: &str) -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.extend(["tests", "fixtures", name]);
    assert!(
        path.is_file(),
        "fixture missing at {}; run scripts/generate-fixture.sh",
        path.display()
    );
    path
}

fn fixture_source() -> MediaSource {
    MediaSource::File(fixture_path("sample.mkv"))
}

fn av_fixture_source() -> MediaSource {
    MediaSource::File(fixture_path("sample_av.mkv"))
}

/// Copies every packet from `input` into `muxer`, returning how many packets
/// were fed in total.
fn copy_all_packets(
    input: &mut MediaInput,
    muxer: &mut MatroskaMuxer,
) -> Result<usize, MediaError> {
    let mut fed = 0;
    while let Some(packet) = input.next_packet()? {
        muxer.write_packet(&packet)?;
        fed += 1;
    }
    Ok(fed)
}

#[test]
fn runtime_abi_matches_compiled_bindings() {
    let versions = nian_media_ffmpeg::runtime_versions().expect("abi check");
    assert_eq!(
        versions.avformat,
        nian_ffmpeg_sys::LIBAVFORMAT_VERSION_MAJOR
    );
    assert_eq!(versions.avcodec, nian_ffmpeg_sys::LIBAVCODEC_VERSION_MAJOR);
    assert_eq!(versions.avutil, nian_ffmpeg_sys::LIBAVUTIL_VERSION_MAJOR);
}

#[test]
fn native_logging_starts_quiet_after_init() {
    FfmpegBackend::new().unwrap();
    // Secret boundary: libav* must be silenced by default so credentialed
    // RTSP URLs can never reach stderr through FFmpeg's own log pipeline.
    assert!(
        nian_media_ffmpeg::native_logging_quiet(),
        "production policy requires AV_LOG_QUIET after init"
    );
}

#[test]
fn probe_reports_fixture_streams() {
    let backend = FfmpegBackend::new().unwrap();
    let report = backend.probe(&fixture_source()).unwrap();

    assert_eq!(report.format_name, "matroska,webm");

    let video = report.video_stream().expect("fixture has a video stream");
    assert_eq!(video.media_type, MediaType::Video);
    assert_eq!(video.codec_name, "mpeg4");
    assert_eq!(video.width, Some(160));
    assert_eq!(video.height, Some(120));
    assert!(video.time_base.is_some());

    let duration = report.duration.expect("fixture duration is known");
    assert!(
        Duration::from_millis(1500) <= duration && duration <= Duration::from_millis(2500),
        "unexpected duration {duration:?}"
    );
}

#[test]
fn reading_packets_yields_keyframed_monotonic_video() {
    let interrupt = InterruptHandle::new();
    let mut input = MediaInput::open(&fixture_source(), &interrupt).unwrap();

    let mut video_packets = 0usize;
    let mut last_dts: Option<i64> = None;
    let mut first_is_keyframe = None;

    while let Some(packet) = input.next_packet().unwrap() {
        assert!(
            !packet.data().is_empty(),
            "packet payload must not be empty"
        );
        if packet.metadata().stream_index == 0 {
            video_packets += 1;
            if first_is_keyframe.is_none() {
                first_is_keyframe = Some(packet.metadata().keyframe);
            }
            let dts = packet.metadata().dts.expect("mpeg4 dts present");
            if let Some(previous) = last_dts {
                assert!(
                    dts > previous,
                    "dts must strictly increase, {previous} -> {dts}"
                );
            }
            last_dts = Some(dts);
        }
    }

    assert!(
        first_is_keyframe.unwrap_or(false),
        "first video packet must be a keyframe"
    );
    // 2 seconds at 10 fps.
    assert!(
        video_packets >= 20,
        "expected ~20 video packets, got {video_packets}"
    );
}

#[test]
fn remux_to_matroska_produces_valid_output() {
    let interrupt = InterruptHandle::new();
    let mut input = MediaInput::open(&fixture_source(), &interrupt).unwrap();

    let output_dir = tempfile::tempdir().unwrap();
    let output_path = output_dir.path().join("remuxed.mkv");

    let mut muxer = MatroskaMuxer::create(&mut input, &output_path, &interrupt).unwrap();
    let mut written = 0usize;
    while let Some(packet) = input.next_packet().unwrap() {
        muxer.write_packet(&packet).unwrap();
        written += 1;
    }
    let finalized = muxer.finalize().unwrap();
    assert_eq!(finalized, output_path);
    assert!(written >= 20);

    let backend = FfmpegBackend::new().unwrap();
    let report = backend.probe(&MediaSource::file(&output_path)).unwrap();
    assert_eq!(report.format_name, "matroska,webm");
    let video = report.video_stream().unwrap();
    assert_eq!(video.codec_name, "mpeg4");
    assert_eq!(video.width, Some(160));

    // The output file must be independently playable/probeable with sane
    // duration (master spec M2 acceptance, exercised early here).
    let duration = report.duration.unwrap();
    assert!(
        Duration::from_millis(1500) <= duration && duration <= Duration::from_millis(2500),
        "remuxed duration {duration:?}"
    );
}

#[test]
fn probe_reports_both_streams_of_av_fixture() {
    let backend = FfmpegBackend::new().unwrap();
    let report = backend.probe(&av_fixture_source()).unwrap();

    assert_eq!(report.streams.len(), 2);
    let video = report.video_stream().expect("video stream");
    assert_eq!(video.codec_name, "mpeg4");
    assert_eq!(video.stream_index, 0);
    let audio = report
        .streams
        .iter()
        .find(|s| s.media_type == MediaType::Audio)
        .expect("audio stream");
    assert_eq!(audio.codec_name, "aac");
    assert_eq!(audio.stream_index, 1);
}

#[test]
fn selecting_audio_only_remaps_stream_indices_and_preserves_duration() {
    let interrupt = InterruptHandle::new();
    let mut input = MediaInput::open(&av_fixture_source(), &interrupt).unwrap();
    let total_streams = input.streams().len();
    assert_eq!(total_streams, 2);

    let output_dir = tempfile::tempdir().unwrap();
    let output_path = output_dir.path().join("audio-only.mkv");
    let mut muxer = MatroskaMuxer::create_with_selection(
        &mut input,
        &output_path,
        &interrupt,
        |info: &MediaStreamInfo| info.media_type == MediaType::Audio,
    )
    .unwrap();

    // Input stream 1 must map to OUTPUT stream 0 — the explicit mapping, not
    // input-index==output-index identity.
    assert_eq!(muxer.mapped_input_stream_indices(), vec![1]);

    let fed = copy_all_packets(&mut input, &mut muxer).unwrap();
    assert!(fed > 20, "video+audio packets expected, fed {fed}");
    muxer.finalize().unwrap();

    let backend = FfmpegBackend::new().unwrap();
    let report = backend.probe(&MediaSource::file(&output_path)).unwrap();
    assert_eq!(
        report.streams.len(),
        1,
        "only the selected stream may appear in the output"
    );
    let only = &report.streams[0];
    assert_eq!(only.media_type, MediaType::Audio);
    assert_eq!(only.codec_name, "aac");
    let duration = report.duration.expect("duration preserved through remap");
    assert!(
        Duration::from_millis(1500) <= duration && duration <= Duration::from_millis(2500),
        "audio-only remux duration {duration:?}"
    );
}

#[test]
fn unselected_stream_packets_are_skipped_deliberately() {
    let interrupt = InterruptHandle::new();
    let mut input = MediaInput::open(&av_fixture_source(), &interrupt).unwrap();

    let output_dir = tempfile::tempdir().unwrap();
    let output_path = output_dir.path().join("video-only.mkv");
    let mut muxer = MatroskaMuxer::create_with_selection(
        &mut input,
        &output_path,
        &interrupt,
        |info: &MediaStreamInfo| info.media_type == MediaType::Video,
    )
    .unwrap();
    assert_eq!(muxer.mapped_input_stream_indices(), vec![0]);

    // Feed the FULL demuxed stream; packets of the unmapped audio stream
    // (index 1) are deliberately skipped by write_packet.
    let mut fed_audio_packets = 0;
    while let Some(packet) = input.next_packet().unwrap() {
        if packet.metadata().stream_index == 1 {
            fed_audio_packets += 1;
        }
        muxer.write_packet(&packet).unwrap();
    }
    assert!(
        fed_audio_packets > 10,
        "test requires audio packets to have been fed, got {fed_audio_packets}"
    );
    muxer.finalize().unwrap();

    let backend = FfmpegBackend::new().unwrap();
    let report = backend.probe(&MediaSource::file(&output_path)).unwrap();
    assert_eq!(report.streams.len(), 1);
    assert_eq!(report.streams[0].media_type, MediaType::Video);
    assert_eq!(report.video_stream().unwrap().width, Some(160));
}

#[test]
fn empty_stream_selection_is_an_error() {
    let interrupt = InterruptHandle::new();
    let mut input = MediaInput::open(&av_fixture_source(), &interrupt).unwrap();
    let output_dir = tempfile::tempdir().unwrap();
    let result = MatroskaMuxer::create_with_selection(
        &mut input,
        &output_dir.path().join("empty.mkv"),
        &interrupt,
        |_| false,
    );
    match result {
        Err(MediaError::WriteFailed { message }) => {
            assert!(message.contains("no input streams"), "{message}");
        }
        other => panic!("expected WriteFailed for empty selection, got {other:?}"),
    }
    assert!(!Path::new(&output_dir.path().join("empty.mkv")).exists());
}

#[test]
fn muxer_keeps_interrupt_callback_valid_after_caller_drops_its_handle() {
    // Regression for the AVIOInterruptCB lifetime invariant: the muxer owns a
    // clone of the handle backing the installed callback, so dropping every
    // caller-held clone mid-recording is safe. With the pre-remediation code
    // the Arc behind the callback could be freed here while FFmpeg still
    // invoked it during av_interleaved_write_frame / finalize.
    let interrupt = InterruptHandle::new();
    let mut input = MediaInput::open(&fixture_source(), &interrupt).unwrap();

    let output_dir = tempfile::tempdir().unwrap();
    let mut muxer = MatroskaMuxer::create(
        &mut input,
        &output_dir.path().join("outlived-handle.mkv"),
        &interrupt,
    )
    .unwrap();
    drop(interrupt); // caller's last clone gone; muxer's own clone remains

    let written = copy_all_packets(&mut input, &mut muxer).unwrap();
    assert!(written >= 20);
    muxer.finalize().unwrap();

    let backend = FfmpegBackend::new().unwrap();
    let report = backend
        .probe(&MediaSource::file(
            output_dir.path().join("outlived-handle.mkv"),
        ))
        .unwrap();
    assert_eq!(report.video_stream().unwrap().codec_name, "mpeg4");
}

#[test]
fn cancellation_after_create_aborts_segment_write() {
    let interrupt = InterruptHandle::new();
    let mut input = MediaInput::open(&fixture_source(), &interrupt).unwrap();
    // Grab a packet up front: after cancel() the input's own interrupt
    // callback would abort reads too, which this test deliberately avoids.
    let first = input
        .next_packet()
        .unwrap()
        .expect("fixture yields packets");

    let output_dir = tempfile::tempdir().unwrap();
    let mut muxer = MatroskaMuxer::create(
        &mut input,
        &output_dir.path().join("cancelled.mkv"),
        &interrupt,
    )
    .unwrap();

    interrupt.cancel();
    match muxer.write_packet(&first) {
        Err(error) => assert!(
            error.is_interrupted(),
            "expected interruption, got {error:?}"
        ),
        Ok(()) => panic!("write must be interrupted after cancel"),
    }
}

#[test]
fn dropping_without_finalize_leaves_partial_file_for_recovery() {
    let interrupt = InterruptHandle::new();
    let mut input = MediaInput::open(&fixture_source(), &interrupt).unwrap();

    let output_dir = tempfile::tempdir().unwrap();
    let output_path = output_dir.path().join("abandoned.mkv");
    let mut muxer = MatroskaMuxer::create(&mut input, &output_path, &interrupt).unwrap();
    let _ = copy_all_packets(&mut input, &mut muxer);
    drop(muxer); // no finalize: crash-recovery semantics

    let file = std::fs::read(&output_path).expect("partial file stays on disk");
    assert!(!file.is_empty(), "dropped segment keeps its written bytes");
}

#[test]
fn remux_preserves_per_packet_keyframe_pattern() {
    // Packet-faithfulness at the flag level: the keyframe pattern of every
    // packet must be identical before and after the stream-copy round trip
    // (the pre-remediation reconstruction path only preserved payload and a
    // handful of fields; this pins that the full packet is what travels).
    let interrupt = InterruptHandle::new();
    let mut input = MediaInput::open(&fixture_source(), &interrupt).unwrap();

    let mut input_pattern = Vec::new();
    let output_dir = tempfile::tempdir().unwrap();
    let output_path = output_dir.path().join("flag-pattern.mkv");
    let mut muxer = MatroskaMuxer::create(&mut input, &output_path, &interrupt).unwrap();
    while let Some(packet) = input.next_packet().unwrap() {
        input_pattern.push((packet.metadata().stream_index, packet.metadata().keyframe));
        muxer.write_packet(&packet).unwrap();
    }
    muxer.finalize().unwrap();
    assert!(input_pattern.len() >= 20);
    assert!(
        input_pattern.iter().any(|(_, keyframe)| *keyframe),
        "fixture must contain keyframes"
    );

    let mut output = MediaInput::open(&MediaSource::file(&output_path), &interrupt).unwrap();
    let mut output_pattern = Vec::new();
    while let Some(packet) = output.next_packet().unwrap() {
        output_pattern.push((packet.metadata().stream_index, packet.metadata().keyframe));
    }
    assert_eq!(input_pattern, output_pattern, "keyframe pattern changed");
}

#[test]
fn cancelled_interrupt_aborts_open() {
    let interrupt = InterruptHandle::new();
    interrupt.cancel();

    let result = MediaInput::open(&fixture_source(), &interrupt);
    match result {
        Err(MediaError::Interrupted { .. }) => {}
        Err(other) => panic!("expected Interrupted, got {other:?}"),
        Ok(_) => panic!("open must fail when the interrupt is pre-cancelled"),
    }
}

#[test]
fn deadline_aborts_open() {
    let interrupt = InterruptHandle::new();
    interrupt.set_deadline_from_now(Duration::from_millis(0));

    let result = MediaInput::open(&fixture_source(), &interrupt);
    match result {
        // Since M3 an expired deadline is TimedOut — distinct from operator
        // cancellation. Depending on where FFmpeg checks the callback first,
        // a plain open error carrying no interrupt classification may also
        // surface; both are acceptable, a hang is not.
        Err(MediaError::TimedOut { .. }) => {}
        Err(MediaError::OpenFailed { .. }) => {}
        Err(other) => panic!("unexpected error {other:?}"),
        Ok(_) => panic!("open must fail with an expired deadline"),
    }
}
