#!/usr/bin/env bash
# Fetches the pinned FFmpeg headers used to generate nian-ffmpeg-sys bindings.
#
# The headers are committed under thirdparty/ffmpeg/ so that normal builds and
# bindgen regeneration do not require network access. Only header files are
# kept; the FFmpeg source itself is not vendored.
#
# Usage: scripts/fetch-ffmpeg-headers.sh
set -Eeuo pipefail

FFMPEG_VERSION="8.0.3"
FFMPEG_TARBALL_SHA256="6136812ea6d4e68bdba27e33c2a94382711cdf4f8602ffef056ff792bd6f9818"
BASE_URL="https://ffmpeg.org/releases"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

tarball="$work_dir/ffmpeg-$FFMPEG_VERSION.tar.xz"

echo "Downloading ffmpeg-$FFMPEG_VERSION.tar.xz ..."
curl --fail --silent --show-error --location \
  --output "$tarball" \
  "$BASE_URL/ffmpeg-$FFMPEG_VERSION.tar.xz"

echo "Verifying sha256 ..."
echo "$FFMPEG_TARBALL_SHA256  $tarball" | sha256sum --check --strict -

echo "Extracting headers ..."
tar -xJf "$tarball" -C "$work_dir"

target="$repo_root/thirdparty/ffmpeg"
rm -rf "$target"
mkdir -p "$target"

# Public entry headers whose transitive #include closure bindgen needs.
ENTRY_HEADERS=(
  libavutil/avutil.h
  libavutil/dict.h
  libavutil/error.h
  libavutil/rational.h
  libavcodec/avcodec.h
  libavcodec/defs.h
  libavcodec/packet.h
  libavcodec/codec_par.h
  libavcodec/codec_id.h
  libavformat/avformat.h
)

source_root="$work_dir/ffmpeg-$FFMPEG_VERSION"
python3 - "$source_root" "$target" "${ENTRY_HEADERS[@]}" <<'PY'
import re
import shutil
import sys
from pathlib import Path

source_root = Path(sys.argv[1])
target = Path(sys.argv[2])
entries = sys.argv[3:]

include_re = re.compile(r'^#\s*include\s*([<"])([^">]+)[">]', re.MULTILINE)

def resolve(included: str, quoted: bool, includer: Path):
    """Map an #include argument to a path inside the source tree."""
    if quoted:
        relative = includer.parent / included
        if relative.is_file():
            return relative
    candidates = [
        source_root / included,                # <libavutil/foo.h> style
        source_root / "libavutil" / included,  # bare "foo.h" from avutil
        source_root / "libavcodec" / included,
        source_root / "libavformat" / included,
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return None

seen: set[Path] = set()
stack: list[tuple[Path, Path]] = []  # (header, pseudo-includer)
for entry in entries:
    resolved = resolve(entry, False, source_root / "libavutil" / "_")
    if resolved is not None:
        stack.append((resolved, resolved))

while stack:
    path, includer = stack.pop()
    if path in seen:
        continue
    seen.add(path)
    text = path.read_text(encoding="utf-8", errors="replace")
    for match in include_re.finditer(text):
        resolved = resolve(match.group(2), match.group(1) == '"', includer)
        if resolved is not None and source_root in resolved.parents:
            stack.append((resolved, resolved))

for path in sorted(seen):
    rel = path.relative_to(source_root)
    destination = target / rel
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, destination)

print(f"kept {len(seen)} headers from include closure")
PY

# libavutil/avconfig.h is generated by FFmpeg's configure step and is not part
# of the source tarball. Headers include it, so vendor a shim with the values
# configure would produce on every platform Nian Vision targets (x86-64 and
# aarch64 are little-endian with fast unaligned access).
cat > "$target/libavutil/avconfig.h" <<'EOF'
/* Generated shim for the build-time header FFmpeg's configure produces.
   See scripts/fetch-ffmpeg-headers.sh; values match x86-64/aarch64 LE. */
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#define AV_HAVE_BIGENDIAN 0
#define AV_HAVE_FAST_UNALIGNED 1
#endif /* AVUTIL_AVCONFIG_H */
EOF

header_count=$(find "$target" -name '*.h' | wc -l)
echo "Copied $header_count headers to $target"
